// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tracker.SensorReadingProcessor.Data;

#nullable disable

namespace Tracker.SensorReadingProcessor.Migrations
{
    [DbContext(typeof(AnalysisDbContext))]
    [Migration("20260630191205_AddAnalysisResultTable")]
    partial class AddAnalysisResultTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Tracker.SensorReadingProcessor.Models.TimeSeriesAnalysisResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Average")
                        .HasColumnType("float");

                    b.Property<double>("PeakValue")
                        .HasColumnType("float");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<double>("TrendSlope")
                        .HasColumnType("float");

                    b.Property<double>("ValleyValue")
                        .HasColumnType("float");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("timeseriesanalysis", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
